# Generated by Django 2.2 on 2019-09-11 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=100.0, max_digits=7)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('txn_id', models.CharField(default=orders.models.txn_id_generator, max_length=32, unique=True, verbose_name='Order Id')),
                ('delivery_expected', models.DateField(blank=True, null=True)),
                ('bill', models.FileField(blank=True, null=True, upload_to='orders/bills/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('user_text', models.TextField(blank=True)),
                ('receiver_name', models.CharField(max_length=64)),
                ('line_1', models.CharField(blank=True, max_length=264)),
                ('line_2', models.CharField(blank=True, max_length=264)),
                ('locality', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=6)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('bill_sms_sent', models.BooleanField(default=False)),
                ('placed_sms_sent', models.BooleanField(default=False)),
                ('rs_sms_sent', models.BooleanField(default=False, verbose_name='Ready to ship sms sent')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NP', 'Payment Pending'), ('PL', 'Order Placed'), ('RS', 'Ready To Ship'), ('SH', 'Shipped'), ('CN', 'Cancelled')], default='NP', max_length=2)),
                ('is_payed', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, to='carts_app.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
